#!/usr/bin/env bash

# -----------------------------------------------------
# Helper functions
# -----------------------------------------------------
function build_secrets {
  local container_hostnames vault_dns_sans

  for ((i=1; i<=VAULT_REPLICAS; i++)); do
    container_hostnames+="vault$i"
  done
  vault_dns_sans="$VAULT_FQDN_NODES $container_hostnames"

  make-ca -o "$SECRETS"
  make-cert vault "$vault_dns_sans" --ca-key "$SECRETS/ca.key" --ca-crt "$SECRETS/ca.crt" -o "$SECRETS"
}

function vault_health {
  local resp http_code content start now elapsed host ready_count

  log_info "Waiting for all Vault nodes to be ready..."

  start=$(date +%s)

  while true; do
    ready_count=0

    for host in $VAULT_FQDN_NODES; do
      resp=$(curl --cacert "$SECRETS/ca.crt" -s -w "%{http_code}" https://$host:$VAULT_API_PORT/v1/sys/health\?uninitcode\=200\&sealedcode\=200)

      http_code="${resp: -3}"
      content="${resp::-3}"

      if [[ "$http_code" == "200" ]]; then
        ((ready_count++))
      fi
    done

    if (( ready_count == VAULT_REPLICAS )); then
      log_info "All Vault nodes are ready."
      return 0
    fi

    now=$(date +%s)
    elapsed=$(( now - start ))

    if (( elapsed > 300 )); then
      log_error "Vault cluster did not become ready within 5 minutes."
      log_error "Last response: $content"
      exit 1
    fi

    sleep 5
  done
}

# -----------------------------------------------------
# Commands
# -----------------------------------------------------

function command_vault_init {
  run_vault_init
}

function command_vault_unseal {
  discover_stack_context
  run_vault_unseal
}

# -----------------------------------------------------
# Stack functions
# -----------------------------------------------------

function run_vault_init {
  local resp http_code content

  log_info "Initialising Vault..."

  resp=$(curl -s -w "%{http_code}" https://vault.$DOMAIN/v1/sys/init --data '{"secret_shares": 4, "secret_threshold": 3}')
  http_code="${resp: -3}"
  content="${resp::-3}"

  if [ "$http_code" == "200" ]; then
    echo "$content" > "$SECRETS/keys.json"
  elif echo "$content" | grep -q '"Vault is already initialized"'; then
    log_info "Vault is already initialised."
  else
    log_error "Failed to initialise Vault."
    exit 1
  fi
}

function run_vault_unseal {
  local key host resp http_code content

  log_info "Unsealing Vault..."

  for key in $(jq -r '.keys[]' "$SECRETS/keys.json"); do
    for host in $VAULT_FQDN_NODES; do
      resp=$(curl --cacert "$SECRETS/ca.crt" -s -w "%{http_code}" https://$host:$VAULT_API_PORT/v1/sys/unseal --data "{\"key\": \"$key\"}")
      http_code="${resp: -3}"
      content="${resp::-3}"

      if [ "$http_code" != "200" ]; then
        log_error "Failed to unseal $host due to [$http_code]: $content"
      fi
    done
  done
}

function stack_check_env {
  if [ ! -d "$SECRETS" ]; then
    log_error "Secrets directory is missing from '$ENVIRONMENT_BASE'."
    exit 1
  fi
}

function stack_discover {
  export VAULT_REPLICAS=$(count "$VAULT_NODES")
}

function stack_tools {
  local tool="$STACK_PATH/tools/$1"
  shift

  if [[ ! -x "$tool" ]]; then
    log_error "$tool doesn't exist or isn't executable."
    exit 1
  fi

  export VAULT_NODE=$(first "$VAULT_FQDN_NODES")
  "$tool" "$@"
}

function stack_env {
  echo
  echo "DOCKER IMAGE       = $VAULT_IMAGE"
  echo "VAULT NODES        = ($VAULT_REPLICAS)"
  list "$VAULT_NODES"
  echo
  echo "VAULT API PORT     = $VAULT_API_PORT"
  echo "VAULT CLUSTER PORT = $VAULT_CLUSTER_PORT"
  echo
  echo "UI                 = https://vault.$DOMAIN"
  echo
}

function stack_deploy {
  build_secrets
  docker stack deploy --detach=true -c vault.yml "$STACK"
  vault_health
  run_vault_init
  run_vault_unseal
}
